#connection parameters
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webapplication?serverTimezone=Europe/Moscow
    username: root
    password: Root2021
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    enabled: true

#default parameters for api/init
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Karachun Maksim
  copyrightFrom: 2021

server:
  port: 8085