#connection parameters
server:
  port: 8085

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webapplication
    username: root
    password: Root2021
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
    enabled: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mail:
    address: http://localhost:8085
    host: smtp.gmail.com
    port: 587
    username: devSocialLine@gmail.com
    password: NtcnNtcn4545
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

profileImage:
  type: 'jpg'
  wight: 120
  height: 120

upload:
  directory: 'upload'

#default parameters for api/init
blog:
  title: NewsPortal
  subtitle: Портал актуальных новостей
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Karachun Maksim
  copyrightFrom: 2021