#connection parameters
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webapplication?serverTimezone=Europe/Moscow
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update